{% set version = '1.0-6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-multiway
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/multiway_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multiway/multiway_{{ version }}.tar.gz
  sha256: fb8d5dd060b32c4607c00121545669b1b0ace95465296f73d35e899cd5f42cf9

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-cmls
  run:
    - r-base
    - r-cmls

test:
  commands:
    - $R -e "library('multiway')"           # [not win]
    - "\"%R%\" -e \"library('multiway')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=multiway
  license: GPL (>= 2)
  summary: Fits multi-way component models via alternating least squares algorithms with optional
    constraints. Fit models include N-way Canonical Polyadic Decomposition, Individual
    Differences Scaling, Multiway Covariates Regression, Parallel Factor Analysis (1
    and 2), Simultaneous Component Analysis, and Tucker Factor Analysis.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - PertuyF
    - tbillet17
    - conda-forge/r

# Package: multiway
# Type: Package
# Title: Component Models for Multi-Way Data
# Version: 1.0-6
# Date: 2019-03-12
# Author: Nathaniel E. Helwig <helwig@umn.edu>
# Maintainer: Nathaniel E. Helwig <helwig@umn.edu>
# Depends: CMLS, parallel
# Description: Fits multi-way component models via alternating least squares algorithms with optional constraints. Fit models include N-way Canonical Polyadic Decomposition, Individual Differences Scaling, Multiway Covariates Regression, Parallel Factor Analysis (1 and 2), Simultaneous Component Analysis, and Tucker Factor Analysis.
# License: GPL (>= 2)
# NeedsCompilation: no
# Packaged: 2019-03-12 22:41:29 UTC; Nate
# Repository: CRAN
# Date/Publication: 2019-03-13 08:20:03 UTC
